name: Build Windows Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          cd build
          cpack -G ZIP

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
        #   files: build/app_hello-*-win64.zip
          files: build/app_hello.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Auto-built Windows binary"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}