name: Simple Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: CMake Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_hello           # 下载时看到的名字
          path: build/app_hello.exe  # 支持通配符：build/**/*.exe