name: vcpkg OpenVDB

on: workflow_dispatch # 手动触发

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true            # 拉取子模块

      - name: Test Python
        run: |
          python test.py ${{ env.VCPKG_ROOT }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

